package com.edw.bean;
// Generated Oct 10, 2012 11:21:20 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Dosen generated by hbm2java
 */
public class Dosen implements java.io.Serializable {

    private String kodedosen;
    private String namadosen;
    private Integer usia;
    private Set mahasiswas = new HashSet(0);

    public Dosen() {
    }

    public Dosen(String kodedosen, String namadosen, int usia) {
        this.kodedosen = kodedosen;
        this.namadosen = namadosen;
        this.usia = usia;
    }

    public Dosen(String kodedosen, String namadosen, int usia, Set mahasiswas) {
        this.kodedosen = kodedosen;
        this.namadosen = namadosen;
        this.usia = usia;
        this.mahasiswas = mahasiswas;
    }

    public String getKodedosen() {
        return this.kodedosen;
    }

    public void setKodedosen(String kodedosen) {
        this.kodedosen = kodedosen;
    }

    public String getNamadosen() {
        return this.namadosen;
    }

    public void setNamadosen(String namadosen) {
        this.namadosen = namadosen;
    }

    public Integer getUsia() {
        return this.usia;
    }

    public void setUsia(Integer usia) {
        this.usia = usia;
    }

    public Set getMahasiswas() {
        return this.mahasiswas;
    }

    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }

    @Override
    public String toString() {
        return "Dosen{" + "kodedosen=" + kodedosen + ", namadosen=" + namadosen + ", usia=" + usia + ", mahasiswas=" + mahasiswas + '}';
    }
}
