package com.edw.bean;
// Generated Oct 10, 2012 11:21:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private Dosen dosen;
     private String nama;

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim) {
        this.nim = nim;
    }
    public Mahasiswa(String nim, Dosen dosen, String nama) {
       this.nim = nim;
       this.dosen = dosen;
       this.nama = nama;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    @Override
    public String toString() {
        return "Mahasiswa{" + "nim=" + nim + ", dosen=" + dosen.getNamadosen() + ", nama=" + nama + '}';
    }




}


